secret_party_core:
    resource: "@SecretPartyCoreBundle/Controller/"
    type:     annotation
    prefix:   /

secret_party_core_thematic_api:
    type:     rest
    resource: SecretParty\Bundle\CoreBundle\Controller\Api\ThematicApiController
    prefix: /api/

secret_party_core_user_api:
    type:     rest
    resource: SecretParty\Bundle\CoreBundle\Controller\Api\UserApiController
    prefix: /api/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile