<?php

namespace SecretParty\Bundle\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ThematicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThematicRepository extends EntityRepository
{
}
